### ISSUE TITLE
BUG: Possible bad arweave transaction data

### ISSUE THREAD

**Issue by jsonpoindexter** [cedriking/ipfsarweave#4]
There is a scenario where if the IPFS gateway responds with a non-200 response the error-body will be put into the arweave transaction data instead of the actual IPFS file data
https://github.com/cedriking/ipfsarweave/blob/b52256528a0d732635296d1906269a35e3fcb236/api/permapin.js#L27

Example bad arweave transaction data:
```html
<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

**Comment by cedriking** [comment]
Thanks for this and the other PR you recently sent @jsonpoindexter , both have been approved and are live 💯
